### PR TITLE
Mark as op required (exclude from help menu)

### PR DESCRIPTION
**Pull request by sponges**

### CODE REVIEW

**Comment by Sponges** [comment]
Update to latest maven version pls :)

**Comment by j0ach1mmall3** [comment]
Joe don't make it require op :( then I can't use it anymore ;(

**Comment by Sponges** [comment]
no, it is just marked as op meaning that it wont appear in the help menu if you arent op

**Comment by j0ach1mmall3** [comment]
k den I'll fix

**Comment by j0ach1mmall3** [comment]
First fix your releases lol I can't bear the commit hashes

**Pull request closed without merging**
